### ISSUE TITLE
[Bug report] Metadata not being saved when using SAF

### ISSUE THREAD

**Issue by BobbyESP** [Kyant0/taglib#2]
When trying to use the library for saving changes into an audio file that is only provided the URI by using the MediaStore API in Android, the library always return `false` when using the `TagLib.saveMetadata()` method. This is the implementation I have:

```kotlin
 fun saveMetadata(newMetadata: Metadata, path: String, fileName: String): Boolean {
        //todo: SEE WHY IT IS NOT SAVED, MAYBE SAF PROBLEM
        try {
            MediaStoreReceiver.getFileDescriptorFromPath(context, path).let { songFd ->
                val fd = songFd?.dup()?.detachFd() ?: throw Exception("File descriptor is null")
                return TagLib.savePropertyMap(
                    fd,
                    fileName = fileName,
                    propertyMap = newMetadata.propertyMap
                )
            }
        } catch (e: Exception) {
            Log.e(
                "ID3MetadataEditorPageViewModel",
                "Error while trying to save metadata: ${e.message}"
            )
            return false
        }
    }
```

And the obtaining of the file descriptor is the next:

```kotlin
    @SuppressLint("Range")
    fun getFileDescriptorFromPath(context: Context, filePath: String): ParcelFileDescriptor? {
        val resolver: ContentResolver = context.contentResolver
        val uri: Uri = MediaStore.Files.getContentUri("external")

        val projection = arrayOf(MediaStore.Files.FileColumns._ID)
        val selection = "${MediaStore.Files.FileColumns.DATA}=?"
        val selectionArgs = arrayOf(filePath)

        resolver.query(uri, projection, selection, selectionArgs, null)?.use { cursor ->
            if (cursor.moveToFirst()) {
                val fileId: Int =
                    cursor.getInt(cursor.getColumnIndex(MediaStore.Files.FileColumns._ID))
                if (fileId == -1) {
                    return null
                } else {
                    val fileUri: Uri = Uri.withAppendedPath(uri, fileId.toString())

                    try {
                        return resolver.openFileDescriptor(fileUri, "r")
                    } catch (e: FileNotFoundException) {
                        Log.e("MediaStoreReceiver", "File not found: ${e.message}")
                    }
                }
            }
        }

        return null
    }
```

**Comment by Kyant0** [comment]
`openFileDescriptor(fileUri, "r")`

I think the problem is here, you should open a read+write fd.

**Comment by BobbyESP** [comment]
Ahh yes, my bad. Later I will try and tell you about it. Really thanks 😂 Silly error

**Comment by Kyant0** [comment]
I encountered this problem as well, haha, or I can't find where is probably wrong, I am not mastered on some Android parts.

**Comment by BobbyESP** [comment]
Hahaha don't worry. Later I try (because I'm not at home rn), but it's probably that, thankss!

**Comment by BobbyESP** [comment]
I'm having this issue when using "rw" mode:

```log
Writing exception to parcel
                                                                                                    android.app.RecoverableSecurityException: com.bobbyesp.spowlo.debug has no access to content://media/external/audio/media/1000022277
                                                                                                    	at com.android.providers.media.MediaProvider.enforceCallingPermissionInternal(MediaProvider.java:10676)
                                                                                                    	at com.android.providers.media.MediaProvider.enforceCallingPermission(MediaProvider.java:10579)
                                                                                                    	at com.android.providers.media.MediaProvider.checkAccess(MediaProvider.java:10703)
                                                                                                    	at com.android.providers.media.MediaProvider.openFileAndEnforcePathPermissionsHelper(MediaProvider.java:9072)
                                                                                                    	at com.android.providers.media.MediaProvider.openFileCommon(MediaProvider.java:8652)
                                                                                                    	at com.android.providers.media.MediaProvider.openFile(MediaProvider.java:8548)
                                                                                                    	at android.content.ContentProvider.openAssetFile(ContentProvider.java:2085)
                                                                                                    	at android.content.ContentProvider.openAssetFile(ContentProvider.java:2146)
                                                                                                    	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:511)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1285)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1249)
```

I do have access to the file, but seems not the permissions to edit it

**Comment by BobbyESP** [comment]
Okay, after some research I found that the problem is that isn't given the neccessary permissions to the app
